package com.panwallet.sdk.error

internal enum class ErrorType(var type: Int) {
    BALANCE(100),
    NOT_DOWNLOADED(200),
    NOT_FROM_PAN(201),
    CONFIG_FAILED(300),
    START_SERVICE_NOT_COMPLETE(301),
    SCHEMA_ERROR(302),
    LOGO_DAPP_ERROR(303),
    DEBUG_CONFIG_NULL(304),
    DAPP_NAME_EMPTY(305),
    HOST_ERROR(350),
    AMOUNT_LESSER_0(351),
    NOT_CONNECT_WALLET(352),
    CHAIN_CONNECT_AS_NETWORK(354),
    CURRENT_WALLET_TYPE_NULL(355)
}